### ISSUE TITLE
Crashes pick,tab

### ISSUE THREAD

**Issue by ptcNN** [Wandang/TwitchPlaysAutoChess#11]
!pick !tab !move and crash every time this error? And tpacLaunch.py **synatx error **+****
```
settings_hotkeys = '' +
                settings_hotkey_ability1 + ',' +
                settings_hotkey_ability2 + ',' +
                settings_hotkey_ability3 + ',' +
                settings_hotkey_ability4 + ',' +
                settings_hotkey_ability5
                settings.append("HOTKEYS = " + settings_hotkeys + "\n")
```
```
!pick 2
trying to move to x:  1610
trying to move to y:  344
trying to move to x:  591
trying to move to y:  37
Traceback (most recent call last):
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 370, in <module>
    setup.start()
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 192, in start
    self.handleTwitchResponse(twitchSocket)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 309, in handleTwitchResponse
    self.gc.findAndExecute(lowerCaseOutput)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 830, in findAndExecute
    self.pickPiece(splitted[1])
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 283, in pickPiece
    self.COORDMAP['chickenAbility5'], 4, (int(target)-1))
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 789, in getLocationOfIntermediatePoint
    aX = int(pointA.x)
AttributeError: 'dict' object has no attribute 'x'

```

**Comment by Wandang** [comment]
Thanks for the reporting. I fixed both issues in the latest push.

Please be so kind and test the new version and report back if the problem still persists somehow

**Comment by ptcNN** [comment]
Different error update :( Using windows btw
```
!pick 1
trying to move to x:  1610
trying to move to y:  344
trying to move to x:  591
trying to move to y:  37
Traceback (most recent call last):
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 365, in <module>
    setup.start()
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 187, in start
    self.handleTwitchResponse(twitchSocket)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 304, in handleTwitchResponse
    self.gc.findAndExecute(lowerCaseOutput)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 830, in findAndExecute
    self.pickPiece(splitted[1])
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 283, in pickPiece
    self.COORDMAP['chickenAbility5'], 4, (int(target)-1))
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 798, in getLocationOfIntermediatePoint
    if(len(idx) == 1):
TypeError: object of type 'int' has no len()
```
```
!tab 1
trying to move to x:  1610
trying to move to y:  344
Traceback (most recent call last):
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 365, in <module>
    setup.start()
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 187, in start
    self.handleTwitchResponse(twitchSocket)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 304, in handleTwitchResponse
    self.gc.findAndExecute(lowerCaseOutput)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 839, in findAndExecute
    self.tabTour(splitted[1])
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 240, in tabTour
    self.COORDMAP['playerPosLast'], 7, (int(playerPlacementID)-1))
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 798, in getLocationOfIntermediatePoint
    if(len(idx) == 1):
TypeError: object of type 'int' has no len()

```
@Wandang
