### ISSUE TITLE
Different problem Move Error

### ISSUE THREAD

**Issue by ptcNN** [Wandang/TwitchPlaysAutoChess#12]
Different error update :( Using windows btw
```
!pick 1
trying to move to x:  1610
trying to move to y:  344
trying to move to x:  591
trying to move to y:  37
Traceback (most recent call last):
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 365, in <module>
    setup.start()
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 187, in start
    self.handleTwitchResponse(twitchSocket)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 304, in handleTwitchResponse
    self.gc.findAndExecute(lowerCaseOutput)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 830, in findAndExecute
    self.pickPiece(splitted[1])
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 283, in pickPiece
    self.COORDMAP['chickenAbility5'], 4, (int(target)-1))
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 798, in getLocationOfIntermediatePoint
    if(len(idx) == 1):
TypeError: object of type 'int' has no len()
```
```
!tab 1
trying to move to x:  1610
trying to move to y:  344
Traceback (most recent call last):
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 365, in <module>
    setup.start()
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 187, in start
    self.handleTwitchResponse(twitchSocket)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\tpacLaunch.py", line 304, in handleTwitchResponse
    self.gc.findAndExecute(lowerCaseOutput)
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 839, in findAndExecute
    self.tabTour(splitted[1])
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 240, in tabTour
    self.COORDMAP['playerPosLast'], 7, (int(playerPlacementID)-1))
  File "C:\Users\ptcN\Documents\GitHub\TwitchPlaysAutoChess\gamecontroller.py", line 798, in getLocationOfIntermediatePoint
    if(len(idx) == 1):
TypeError: object of type 'int' has no len()

```
@Wandang

**Comment by Wandang** [comment]
Thanks for reporting. I fixed the issue as well. Additionally I tested most commands (move,sell,pick,tab,reroll,buyXP,grab item,give item to hero) to make sure this state works
